### ISSUE TITLE
Rename package to messagecloud/gateway

### ISSUE THREAD

**Issue by ethanbray** [MessageCloud/txtnation-gateway-php#11]
For version 2, it would be good to re-name this package entirely to be more in line with our brand.

**Comment by Syriane-B** [comment]
Hi, I'll be happy to work on this

**Comment by ethanbray** [comment]
Hi, thanks for helping out. You'll need to change the `name` of the library in the `composer.json` file to `messagecloud/gateway`. Once you've created a PR for that, we can merge it and we'll handle the Packagist changes on our side.
